import type { HierarchyLevel } from "../../types/api"

export const DEFAULT_COLUMN_VISIBILITY: Record<HierarchyLevel, Record<string, boolean>> = {
    project: {
        project_id: true,
        total_count: true,
        subject_count: true,
        sample_count: true,
        b_cell: true,
        b_cell_pct: false,
        cd8_t_cell: true,
        cd8_t_cell_pct: false,
        cd4_t_cell: true,
        cd4_t_cell_pct: false,
        nk_cell: true,
        nk_cell_pct: false,
        monocyte: true,
        monocyte_pct: false,
    },
    subject: {
        project_id: false,
        subject_id: true,
        condition: true,
        age: false,
        sex: true,
        treatment: true,
        response: true,
        sample_type: true,
        total_count: true,
        sample_count: true,
        b_cell: true,
        b_cell_pct: false,
        cd8_t_cell: true,
        cd8_t_cell_pct: false,
        cd4_t_cell: true,
        cd4_t_cell_pct: false,
        nk_cell: true,
        nk_cell_pct: false,
        monocyte: true,
        monocyte_pct: false,
    },
    sample: {
        project_id: false,
        subject_id: true,
        condition: true,
        age: false,
        sex: false,
        treatment: true,
        response: true,
        sample_type: true,
        sample_id: true,
        time_from_treatment_start: true,
        b_cell: true,
        b_cell_pct: false,
        cd8_t_cell: true,
        cd8_t_cell_pct: false,
        cd4_t_cell: true,
        cd4_t_cell_pct: false,
        nk_cell: true,
        nk_cell_pct: false,
        monocyte: true,
        monocyte_pct: false,
        total_count: true,
    },
    cell: {
        project_id: false,
        subject_id: false,
        condition: false,
        age: false,
        sex: false,
        treatment: false,
        response: false,
        sample_type: false,
        sample_id: true,
        time_from_treatment_start: false,
        cell_type_name: true,
        cell_count: true,
        cell_percentage: true,
        total_count: true,
    },
}

export function getDefaultColumnVisibility(level: HierarchyLevel): Record<string, boolean> {
    return { ...DEFAULT_COLUMN_VISIBILITY[level] }
}
